# Generated by Django 4.2.5 on 2023-10-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='prod',
            new_name='product',
        ),
    ]
